-- ==========================================================
-- Configure Snowflake Session
-- ==========================================================
-- USE ROLE GITHUB_ACTIONS_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA GOLD;

-- ==========================================================
-- CUSTOMER SURROGATE KEY
-- ==========================================================

CREATE OR REPLACE SEQUENCE CUSTOMER_KEY_SEQ
START = 1
INCREMENT = 1;

-- Mapping table (Business Key → Surrogate Key)
CREATE OR REPLACE TABLE CUSTOMER_KEYS AS
SELECT
    CUSTOMER_KEY_SEQ.NEXTVAL AS CUSTOMER_KEY,
    CUSTOMER_ID
FROM GOLD.DIM_CUSTOMERS;

-- Dimension Table
CREATE OR REPLACE TABLE GOLD.DIM_CUSTOMERS AS
SELECT DISTINCT
    CK.CUSTOMER_KEY,
    SC.CUSTOMER_ID,
    SC.CUSTOMER_UNIQUE_ID,
    SC.CUSTOMER_ZIP_CODE_PREFIX,
    SC.CUSTOMER_CITY,
    SC.CUSTOMER_STATE
FROM SILVER.CUSTOMERS SC
INNER JOIN CUSTOMER_KEYS CK
    ON SC.CUSTOMER_ID = CK.CUSTOMER_ID;

-- ==========================================================
-- PRODUCT SURROGATE KEY
-- ==========================================================

CREATE OR REPLACE SEQUENCE PRODUCT_KEY_SEQ
START = 1
INCREMENT = 1;

CREATE OR REPLACE TABLE PRODUCT_KEYS AS
SELECT
    PRODUCT_KEY_SEQ.NEXTVAL AS PRODUCT_KEY,
    PRODUCT_ID
FROM GOLD.DIM_PRODUCTS;

CREATE OR REPLACE TABLE GOLD.DIM_PRODUCTS AS
SELECT DISTINCT
    PK.PRODUCT_KEY,
    SP.PRODUCT_ID,
    SP.PRODUCT_CATEGORY_NAME,
    SP.PRODUCT_NAME_LENGTH,
    SP.PRODUCT_DESCRIPTION_LENGTH,
    SP.PRODUCT_PHOTOS_QTY,
    SP.PRODUCT_WEIGHT_G,
    SP.PRODUCT_LENGTH_CM,
    SP.PRODUCT_HEIGHT_CM,
    SP.PRODUCT_WIDTH_CM
FROM SILVER.PRODUCTS SP
INNER JOIN PRODUCT_KEYS PK
    ON SP.PRODUCT_ID = PK.PRODUCT_ID;

-- ==========================================================
-- SELLER SURROGATE KEY
-- ==========================================================

CREATE OR REPLACE SEQUENCE SELLER_KEY_SEQ
START = 1
INCREMENT = 1;

CREATE OR REPLACE TABLE SELLER_KEYS AS
SELECT
    SELLER_KEY_SEQ.NEXTVAL AS SELLER_KEY,
    SELLER_ID
FROM GOLD.DIM_SELLERS;

CREATE OR REPLACE TABLE GOLD.DIM_SELLERS AS
SELECT DISTINCT
    SK.SELLER_KEY,
    SS.SELLER_ID,
    SS.SELLER_ZIP_CODE_PREFIX,
    SS.SELLER_CITY,
    SS.SELLER_STATE
FROM SILVER.SELLERS SS
INNER JOIN SELLER_KEYS SK
    ON SS.SELLER_ID = SK.SELLER_ID;

-- ==========================================================
-- FACT PAYMENTS
-- Grain:
-- One payment transaction per order.
-- ==========================================================

CREATE OR REPLACE TABLE GOLD.FACT_PAYMENTS AS

SELECT
    SP.ORDER_ID,
    SP.PAYMENT_SEQUENTIAL,

    -- Foreign Key
    CK.CUSTOMER_KEY,

    -- Attributes
    SO.ORDER_STATUS,
    SP.PAYMENT_TYPE,
    SP.PAYMENT_INSTALLMENTS,
    SO.ORDER_PURCHASE_TIMESTAMP,

    -- Measure
    SP.PAYMENT_VALUE

FROM SILVER.ORDER_PAYMENTS SP

INNER JOIN SILVER.ORDERS SO
    ON SP.ORDER_ID = SO.ORDER_ID

INNER JOIN CUSTOMER_KEYS CK
    ON SO.CUSTOMER_ID = CK.CUSTOMER_ID;

-- ==========================================================
-- FACT SALES
-- Grain:
-- One row per order item.
-- ==========================================================

CREATE OR REPLACE TABLE GOLD.FACT_SALES AS

SELECT

    -- Degenerate Dimension
    OI.ORDER_ID,
    OI.ORDER_ITEM_ID,

    -- Foreign Keys
    CK.CUSTOMER_KEY,
    PK.PRODUCT_KEY,
    SK.SELLER_KEY,

    -- Transaction Attributes
    O.ORDER_STATUS,
    O.ORDER_PURCHASE_TIMESTAMP,
    OI.SHIPPING_LIMIT_DATE,

    -- Delivery Information
    O.ORDER_ESTIMATED_DELIVERY_DATE,
    O.ORDER_DELIVERED_CARRIER_DATE,
    O.ORDER_DELIVERED_CUSTOMER_DATE,

    -- Measures
    OI.PRICE AS SALES_AMOUNT,
    OI.FREIGHT_VALUE AS SHIPPING_COST

FROM SILVER.ORDER_ITEMS OI

INNER JOIN SILVER.ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID

INNER JOIN CUSTOMER_KEYS CK
    ON O.CUSTOMER_ID = CK.CUSTOMER_ID

INNER JOIN PRODUCT_KEYS PK
    ON OI.PRODUCT_ID = PK.PRODUCT_ID

INNER JOIN SELLER_KEYS SK
    ON OI.SELLER_ID = SK.SELLER_ID;

-- ==========================================================
-- FACT REVIEWS
-- Grain:
-- One review per order.
-- ==========================================================

CREATE OR REPLACE TABLE GOLD.FACT_REVIEWS AS

SELECT

    -- Composite Key
    SR.REVIEW_ID,
    SR.ORDER_ID,

    -- Foreign Key
    CK.CUSTOMER_KEY,

    -- Attributes
    SR.REVIEW_CREATION_DATE,
    SR.REVIEW_ANSWER_TIMESTAMP,

    -- Measure
    SR.REVIEW_SCORE

FROM SILVER.ORDER_REVIEWS SR

INNER JOIN SILVER.ORDERS SO
    ON SR.ORDER_ID = SO.ORDER_ID

INNER JOIN CUSTOMER_KEYS CK
    ON SO.CUSTOMER_ID = CK.CUSTOMER_ID;