-- ==========================================================
-- Infrastructure Bootstrap
-- Version : 1.0
--
-- Purpose:
-- Creates the core Snowflake infrastructure required before
-- the CI/CD pipeline can deploy objects.
--
-- This script is executed manually by ACCOUNTADMIN.
-- GitHub Actions DOES NOT execute this script.
-- ==========================================================
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE WAREHOUSE compute_wh 
INITIALLY_SUSPENDED=TRUE 
AUTO_RESUME=TRUE 
AUTO_SUSPEND=600
MIN_CLUSTER_COUNT=1
MAX_CLUSTER_COUNT=4
SCALING_POLICY=STANDARD
WAREHOUSE_SIZE='small';
CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;


CREATE ROLE IF NOT EXISTS GITHUB_ACTIONS_ROLE;
GRANT USAGE ON WAREHOUSE compute_wh TO ROLE GITHUB_ACTIONS_ROLE;
GRANT ALL ON DATABASE ECOMMERCE_DB TO ROLE GIThub_ACTIONS_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE GITHUB_ACTIONS_ROLE;
GRANT  ALL PRIVILEGES ON  FUTURE SCHEMAS IN DATABASE ECOMMERCE_DB TO ROLE GITHUB_ACTIONS_ROLE;

CREATE USER IF NOT EXISTS github_actions
PASSWORD='<set_manually>'
DEFAULT_ROLE=GITHUB_ACTIONS_ROLE
DEFAULT_WAREHOUSE=compute_wh
DEFAULT_NAMESPACE = ECOMMERCE_DB.RAW;

GRANT ROLE GITHUB_ACTIONS_ROLE TO USER github_actions;