
-- USE ROLE github_actions;
-- CREATE  WAREHOUSE IF NOT EXISTS compute_wh
-- WAREHOUSE_SIZE ='small'
-- INITIALLY_SUSPENDED=TRUE
-- MIN_CLUSTER_COUNT=1
-- MAX_CLUSTER_COUNT=4
-- AUTO_SUSPEND=60
-- AUTO_RESUME=TRUE
-- SCALING_POLICY=standard;
-- CREATE DATABASE IF NOT EXISTS ecommerce_db;
USE DATABASE ECOMMERCE_DB;
USE WAREHOUSE compute_wh;
CREATE  SCHEMA IF NOT EXISTS raw;
CREATE  SCHEMA IF NOT EXISTS bronze;
CREATE  SCHEMA IF NOT EXISTS silver;
CREATE  SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
USE WAREHOUSE compute_wh;
USE DATABASE ecommerce_db;
USE SCHEMA RAW;
CREATE  STAGE IF NOT EXISTS ecom_stage;
CREATE  FILE FORMAT IF NOT EXISTS csv_format
TYPE='CSV'
SKIP_HEADER = 1 
FIELD_OPTIONALLY_ENCLOSED_BY='"';
CREATE FILE FORMAT IF NOT EXISTS infer_schema_csv 
TYPE='CSV'
PARSE_HEADER=TRUE
FIELD_OPTIONALLY_ENCLOSED_BY='"';