USE WAREHOUSE compute_wh;
USE DATABASE ecommerce_db;
CREATE  SCHEMA IF NOT EXISTS raw;
CREATE  SCHEMA IF NOT EXISTS bronze;
CREATE  SCHEMA IF NOT EXISTS silver;
CREATE  SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE SCHEMA RAW;

CREATE  FILE FORMAT IF NOt EXISTS csv_format
TYPE='CSV'
SKIP_HEADER = 1 
FIELD_OPTIONALLY_ENCLOSED_BY='"';
CREATE FILE FORMAT IF NOT EXISTS infer_schema_csv 
TYPE='CSV'
PARSE_HEADER=TRUE
FIELD_OPTIONALLY_ENCLOSED_BY='"';